name: Contenu
favicon: null
layout_spectrum: 0.6528410057071596
typography_spectrum: 0.6418518570717424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6576250656507909
  lightness: 0.12452414352446795
  saturation: 0.12722494429908693
  rhythmicContrast: 0.6760766834486276
purpose: []
